services:
  app:
    depends_on:
      - postgres
    container_name: nest_architecture
    restart: unless-stopped
    command: npm run start:dev
    env_file: ./.env
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - '4000:4000'
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: $POSTGRES_PORT
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DATABASE: $POSTGRES_DATABASE
    networks:
      - nest_architecture

  postgres:
    container_name: nest_architecture_postgres
    image: postgres
    ports:
      - '5433:$POSTGRES_PORT'
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DATABASE
    networks:
      - nest_architecture
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  postgres_migrations:
    container_name: nest_architecture_postgres_migrations
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: docker/Dockerfile
    command: npm run migrations:run
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: $POSTGRES_PORT
    networks:
      - nest_architecture

networks:
  nest_architecture:
    driver: bridge
